name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # Replace this with your actual RSS feed or Medium/Hashnode/Dev.to url
          # Example: https://medium.com/feed/@YOUR_MEDIUM_USERNAME
          # Example: https://YOUR_HASHNODE_USERNAME.hashnode.dev/rss.xml
          feed_list: "YOUR_RSS_FEED_URL"
